# -*- coding: utf-8 -*-
"""Cópia de PYTHON POO.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/156jCoQGnNHdf8W4BPoddEfzelJ1L9_VO
"""

veiculo1 = {'marca': 'GM', 'rodas': 4, 'cor': 'branco', 'ano':2000}

veiculo2 = {'marca': 'GM', 'rodas': 4, 'cor': 'branco', 'ano':2000}

print(veiculo1)
print(veiculo2)

veiculo1['ano'] = 2020

print(veiculo1)

def criarVeiculo (marca, rodas, cor, ano):
  v = {
      "marca": marca, "rodas": rodas, "cor": cor,"ano": ano
  }
  return v

def alteraVeiculo (veiculo, chave, valor):
  veiculo[chave] = valor


veiculo1 = criarVeiculo("Fiat", 4, "preto", 2020)
print(veiculo1)

alteraVeiculo(veiculo1, 'marca', 'Ford')
print(veiculo1)

#definicão de classe: onde se coloca as caracteristicas do objeto e as ações que ele pode tomar em relação ao código
#criando uma classe

class Veiculo():  #sempre inicia com letra mauiscula
  def __init__(self, marca, rodas, cor, ano): #função construtora da classe
    #atributos (variaveis) do objeto
    self.marca = marca
    self.rodas = rodas
    self.cor = cor
    self.ano = ano


v1 = Veiculo("Ford", 4, "preta", 1998)
v2 = Veiculo("Honda", 2, "Verde", 2010)
#para print, sempre colocar o objeo, o "." e a chave desejada
print(v1.marca)
print(v1.ano)

class Animal():
  def __init__(self, especie, porte, alimentacao):
    self.especie = especie
    self.porte = porte
    self.alimentacao = alimentacao
    self.cauda = True
    self.alado = False


  def listaAtributos(self):
    print(self.especie, self.porte,self.alimentacao, self.cauda, self.alado)

  def modPorte(self, novoPorte):
    self.porte = novoPorte


animal1 = Animal("canina", "pequeno", "onivoro")


animal1.modPorte("Medio")
print(animal1.porte)


animal1.listaAtributos()

class Veiculo():
  def __init__(self,marca,rodas,cor,ano, modelo):
    self.marca = marca
    self.rodas = rodas
    self.cor = cor
    self.ano = ano
    self.ligado = False
    self.desligado = True
    self.modelo = modelo
    self.automatico = True


  def ligar(self):
    self.ligado = True
    print('Ligado')

  def desligar(self):
    self.desligado = True
    print('Desligado')

  def aumentaAno(self, sobeAno):
    self.ano += sobeAno

  def diminuiAno(self, desceAno):
    self.ano -= desceAno

  def modCor(self, novacor):
    self.cor = novacor

v1 = Veiculo ("Ford", 4, "Verde", 2022, "Sedan")

print(v1.modelo)

v1.modCor("Azul")
print(v1.cor)

v1.aumentaAno(3)
print(v1.ano)